### ISSUE TITLE
Question regarding usage with 3ds.guide

### ISSUE THREAD

**Issue by sora10pls** [d0k3/SafeCtrTransfer#10]
Would it be possible for SafeCTRTransfer to have an A9LH install feature? It's been on my mind for a bit recently but I've never really gotten around to asking if it would be possible.

Ideally...

ARM9 code exec => SafeCTRTransfer => When done, return and then install A9LH from menu because user is now on 2.1.0 => After installed, restore NAND backup

Like I said: I don't know if this would even be possible, but I figured I'd ask. :)

**Comment by d0k3** [comment]
Not possible, otherwise we would have long done this. For the OTP to become accessible, enabling A9LH install, you need to actually boot in 2.1.
