### ISSUE TITLE
[v0.0.5] Lower screen doesn't initialize when launched from Brahma2

### ISSUE THREAD

**Issue by yuriks** [d0k3/SafeCtrTransfer#11]
On an old3DS 9.2.0-20U, I launched SafeCtrTransfer.bin from the v0.0.5 archive, using Brahma2 from the homebrew starter kit. The payload and transfer worked correctly, but the bottom screen was not re-initialized, and was garbled and unreadable:

![image](https://cloud.githubusercontent.com/assets/341401/25553200/bcdc8a2e-2c61-11e7-9a36-8f0465e72777.png)

**Comment by d0k3** [comment]
Use the included .3dsx file instead of that Brahma version. Screen init problems are actually quite common in Brahma2.
