### ISSUE TITLE
CTR Transfer not Finished

### ISSUE THREAD

**Issue by Arktoja** [d0k3/SafeCtrTransfer#12]
Info

MicroSD Card - 63205MB/63984MB (Green ,I assume it's OK)
System Status - USA N3DS (retail) (Green ,I assume it's OK)
Transfer File - 2.1.0-4U...._o3ds.bin (Yellow, i do not know why)
SHA256 Check - not started
Preparations - firm load failed (Red, error here I think)
Backup Status - not started
Install Status - not started

Please help.

**Comment by d0k3** [comment]
Looks like this is not one of the images Plailect provides - where did you get it from? If it is supposed to be one, maybe redownload?

**Comment by d0k3** [comment]
Okay, this is missing info and I assume @Arktoja already found the problem on his side by this point. Closing this now...

**Comment by Arktoja** [comment]
Sorry I didn't reply, but the issue is still the same but sometimes it say something around image cannot be loaded. I downloaded it directly from the 3ds hack guide.

**Comment by d0k3** [comment]
Okay, then try a different SD card and let me know if that works for you.

**Comment by Arktoja** [comment]
Ok, I'll buy a new one

**Comment by Arktoja** [comment]
I have no idea what exactly happen but I just use the guiformat app suggested in the guide to format my sd card and now I manage to install successfully install everything with no issues.

Thanks for the help.
