### ISSUE TITLE
Preparations error

### ISSUE THREAD

**Issue by JollySlayer** [d0k3/SafeCtrTransfer#14]
I am following the guide.3ds instructions, after starting SafeCTRTransver the program runs through everything up until Preparations after which the message file transfer failed appears after starting image cleanup in yellow. I have looked but have been unable to resolve the issue based on the troubleshooting guide found in guide.3ds or other threads on the internet.
The Info on the screen is:
MicroSD Card -  3205MB/7376MB free
System Status - EUR N3DS (retail)
Transfer File - 2.1.0-4e...03ds.bin
SHA256 Check - matches .sha file
Preparations - file transfer failed (which is the only one coloured red, the other text all appears in green)
What should I do?

**Comment by d0k3** [comment]
Well... did you see "file transfers..." (in yellow) for a while before it turned to red? Also, is there anything special about your NAND? Did you enter the homemenu in this NAND at least once?

**Comment by JollySlayer** [comment]
The error seems to be fixed after switching to a different sd card and repeating the process.
