### ISSUE TITLE
NAND backup defaultly located in /ctrtransfer but not /files9

### ISSUE THREAD

**Issue by MelonGx** [d0k3/SafeCtrTransfer#3]
..... which makes the NAND restoration by D9WIP/Hourglass9 inconvenient.
(I can manually move the NAND backup to /files9 via PC or GM9 but noobs can't.)

**Comment by MelonGx** [comment]
BTW, the NAND backup dumped by SafeCTRTransfer hasn't got any .SHA.

**Comment by d0k3** [comment]
The Guide(tm) tells you to use GodMode9 for the NAND backup restore now. @Plailect's instructions make it easy enough for everyone to use GodMode9. I won't tell anyone what tools to use, but I won't change this either.

Leaving this open cause, yes, an .SHA file makes sense to accompany the NAND backup.

**Comment by d0k3** [comment]
See: https://github.com/d0k3/SafeCTRTransfer/commit/dacd65f31bee06fd8ea70e111d9a8889ed9415ce
