### ISSUE TITLE
SafeCTRtransfer no work?

### ISSUE THREAD

**Issue by SamusMH** [d0k3/SafeCtrTransfer#5]
I have the files but once I try to run it it just keeps saying "CTR Transfer not finished! No changes written to NAND" and when I try the troubleshooting idea with Godmode9 then that doesn't even load, what else am I suppose to do?

**Comment by d0k3** [comment]
You know there is a bottom screen with info, too? What does it say?

**Comment by SamusMH** [comment]
It come up as "Micro SD 926MB/3716MB free" then the rest just say "not started"

**Comment by d0k3** [comment]
So, well... if that comes up, and it is in red, did you thin about the solution being that you have too little space left? Read the guide better. You need to habe enough space free for at least one NAND backup.

**Comment by SamusMH** [comment]
fixed it now thanks for the info i would have been at the beginning stage forever, again thank you
