### ISSUE TITLE
SafeCTRTransfer grey screen

### ISSUE THREAD

**Issue by Nelis77** [d0k3/SafeCtrTransfer#6]
From Old 3DS 4.1.0-0E version downgrading to 2,1.0 as via the 3dsGuide.
Started SafeCTRTransfer.nds from flashcard and selected 4.x SafeCTRTransfer.
Copy and install succesfull, press A.
I went to system and profiles. Opened Nintendo DS profile.
And then a grey screen, No boot into SaveCTRTransfer.

What did I do wrong. How to fix this?

**Comment by MelonGx** [comment]
Have you tried the GW-MSET compatible payload either?
(Launcher.dat and GW blue-card .NDS, it should have better compatibility than CakeROPS to frankenfirmwares.)

**Comment by TheYugito** [comment]
I have tried both methods: The GW-MSET one using the GW_installer.nds and SafeCTRTransfer.nds but no results. GW-MSET gives me an error and the other one gives me the infinite grey screen.

Old 3DS 4.5.0-0E and following the 3ds.guide

Is there anyway to fix this ?

Thanks

**Comment by d0k3** [comment]
There was a problem with MSET in the last release...

Could you try this test build and let me know if it works for you?
https://transfer.sh/keixy/SafeCTRTransfer-20170417-222419.zip

**Comment by TheYugito** [comment]
Ah yes it works. It has booted into SafeCTRTransfer.

(I tried the _SafeCTRTransfer.nds_ with _SafeCTRTransfer.dat_)

Thank you very much !

If i have any other problems with it i will report it back.

**Comment by d0k3** [comment]
Alright, new release coming, closing this issue now.
