### ISSUE TITLE
SafeCTRTransfer error

### ISSUE THREAD

**Issue by sabien2001** [d0k3/SafeCtrTransfer#9]
im trying to install CFW on 11.3 i accidently deleted my 11.3 NAND.bin file so i tries a 9.2.0 transfer but after i do the transfer i get an error saying "Failed to find CTRNAND FIRM" press any button to reboot what should i do please help/

**Comment by d0k3** [comment]
SafeCTRTransfer is only for transfers to FW 2.1. Consult the Guide and use GodMode9!
